allowBuilds:
  "@google/genai": false
  "@parcel/watcher": false
  "@sentry/cli": true
  "@swc/core": false
  bufferutil: false
  esbuild: true
  protobufjs: false
  sharp: true
  unrs-resolver: false
